name = "simple-k"
license = "MIT"
licenselink = "https://github.com/KervyN/simple-k/blob/master/LICENSE.md"
description = "Minimalistic Hugo theme"
min_version = 0.14

tags = ["KervyN", ]
features = ["blog", ]

[author]
    name = "KervyN"
    homepage = "https://www.kervyn.de/"
    source_repo = "https://github.com/KervyN/simple-k"
